# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50917758efd788afb274fcf47298567dcda2da14faa31389cc3a2a0130180421991e4de9417a551a6e02306c57878b97c1f857c3a032f3e506d60f742ff90da8

test:
  secret_key_base: 24ed3a1ea1f9933972611ba116adcecb005ae3db770e2024dfe367159bf690b9b60e004a6527dbafafa763d226724b815b5333040fe52296a7bebf16795931b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
